### ISSUE TITLE
Merge/deprecation

### ISSUE THREAD

**Issue by Flydiverny** [Wyrrrd/IndustrialDisplayPlates#18]
Hi! 👋 

I just saw your question on my fork on the [mod portal](https://mods.factorio.com/mod/DisplayPlates/discussion/612cec358877fbdba5e74a38) 
Haven't been looking at the mod portal for awhile, so posting here where I know I'll get notified of answers 😆.
But for sure if you want to use some or all of my changes into the mod feel free! :)

I did considering making a PR, but it was my first time messing with mods so I didn't want to cause issues for others if my lua was crap but since playing with my brother I needed to publish it 😄

**Comment by Wyrrrd** [comment]
I am currently planning on retiring my version of the mod, since I can't find the time to maintain it. In the next time, you will get some new threads in the mod portal as well as some PRs on Github to merge the new languages and some fixes into your mod. 

(Wouldn't want to lose the collection of good ideas and work of others because of my time management 😅)

**Comment by Wyrrrd** [comment]
Oh and I will not be gone for good, if you need help in logic or code, feel free to ask :)
